# Consuming the work queue
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: message-queue
    component: consumer
    chapter: jobs
  name: consumers
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app: message-queue
        component: consumer
        chapter: jobs
    spec:
      containers:
        - name: worker
          image: jdexx/kuard-amd64:1
          imagePullPolicy: Always
          args:
            - '--keygen-enable'
            - '--keygen-exit-on-complete'
            - '--keygen-memq-server=http://quque:8080/memq/server'
            - '--keygen-memq-queue=keygen'
      restartPolicy: OnFailure
